-- spaceduck dark palette

local function hi()
  return require('highlighter')
end

local M = {}

---@param c spaceduck.palette
---@return table<string, palette.HighlightAttrs>
function M.setup(c)
  return {
    ui = {
      Normal = {
        fg = c.cream.hex,
        ctermfg = c.cream.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      ColorColumn = {
        bg = c.dark_blue.hex,
        ctermbg = c.dark_blue.cterm,
      },
      CursorColumn = {
        bg = c.dark_blue.hex,
        ctermbg = c.dark_blue.cterm,
      },
      Conceal = {
        fg = c.grey_purple.hex,
        ctermfg = c.grey_purple.cterm,
      },
      Cursor = {
        fg = c.blackish.hex,
        ctermfg = c.blackish.cterm,
        bg = c.grey.hex,
        ctermbg = c.grey.cterm,
      },
      CursorIM = { link = 'Cursor' },
      CursorLine = {
        bg = c.dark_blue.hex,
        ctermfg = c.dark_blue.cterm,
      },
      CursorLineNr = {
        fg = c.greyer.hex,
        ctermfg = c.greyer.cterm,
        bg = c.dark_blue.hex,
        ctermbg = c.dark_blue.cterm,
      },
      Directory = {
        fg = c.cyan.hex,
        ctermfg = c.cyan.cterm,
      },
      EndOfBuffer = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      TermCursor = { link = 'Cursor' },
      ErrorMsg = {
        fg = c.red.hex,
        ctermfg = c.red.cterm,
      },
      VertSplit = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      Folded = {
        fg = c.grey_purple.hex,
        ctermfg = c.grey_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      FoldColumn = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      SignColumn = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      IncSearch = {
        fg = c.white.hex,
        ctermfg = c.white.cterm,
        bg = c.dark_purple.hex,
        ctermbg = c.dark_purple.cterm,
      },
      LineNr = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      MatchParen = {
        fg = c.white.hex,
        ctermfg = c.white.cterm,
        bg = hi().darken(c.dark_purple.hex, 0.50, c.dark_purple.hex),
        ctermbg = c.dark_purple.cterm,
        bold = true,
      },
      ModeMsg = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      MoreMsg = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      NonText = { link = 'EndOfBuffer' },
      Question = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      QuickFixLine = {
        fg = c.cream.hex,
        ctermfg = c.cream.cterm,
        bg = c.dark_blue.hex,
        ctermbg = c.dark_blue.cterm,
      },
      Search = {
        fg = c.white.hex,
        ctermfg = c.white.cterm,
        bg = c.grey_purple.hex,
        ctermbg = c.grey_purple.cterm,
      },
      SpecialKey = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      Whitespace = { link = 'EndOfBuffer' },
      WinSeparator = { link = 'VertSplit' },
    },

    menu = {
      Pmenu = {
        fg = c.cream.hex,
        ctermfg = c.cream.cterm,
        bg = c.dark_grey.hex,
        ctermbg = c.dark_grey.cterm,
      },
      PmenuSel = {
        fg = c.white.hex,
        ctermfg = c.white.cterm,
        bg = c.dark_purple.hex,
        ctermbg = c.dark_purple.cterm,
      },
      PmenuSbar = { bg = c.dark_purple.hex, ctermbg = c.dark_purple.cterm },
      PmenuThumb = { bg = c.grey_purple.hex, ctermbg = c.grey_purple.cterm },
      WildMenu = {
        fg = c.black.hex,
        ctermfg = c.black.cterm,
        bg = c.greyer.hex,
        ctermbg = c.greyer.cterm,
      },
    },

    status = {
      StatusLine = {
        fg = c.cream.hex,
        ctermfg = c.cream.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
        reverse = true,
      },
      StatusLineTerm = { link = 'StatusLine' },
      StatusLineTermNC = {
        fg = c.black.hex,
        ctermfg = c.black.cterm,
        bg = c.dark_purple.hex,
        ctermbg = c.dark_purple.cterm,
        reverse = true,
      },
      StatusLineNC = { link = 'StatusLineTermNC' },
      SpellBad = { fg = c.red.hex, ctermfg = c.red.cterm, underline = true },
      SpellLocal = { fg = c.cream.hex, ctermfg = c.cream.cterm, underline = true },
      SpellCap = { fg = c.green.hex, ctermfg = c.green.cterm, underline = true },
      SpellRare = { fg = c.yellow.hex, ctermfg = c.yellow.cterm, underline = true },
      WarningMsg = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
    },

    tabs = {
      TabLine = {
        fg = c.black.hex,
        ctermfg = c.black.cterm,
        bg = c.grey.hex,
        ctermbg = c.grey.cterm,
      },
      TabLineFill = {
        fg = c.grey.hex,
        ctermfg = c.grey.cterm,
        bg = c.black.hex,
        ctermbg = c.black.cterm,
      },
      TabLineSel = {
        fg = c.greyer.hex,
        ctermfg = c.greyer.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
    },

    visual = {
      Visual = { bg = c.dark_grey.hex, ctermbg = c.dark_grey.cterm },
      VisualNOS = { link = 'Visual' },
    },

    diff = {
      DiffAdd = {
        fg = c.green.hex,
        ctermfg = c.green.cterm,
        bg = c.dark_grey.hex,
        ctermbg = c.dark_grey.cterm,
      },
      DiffChange = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.dark_grey.hex,
        ctermbg = c.dark_grey.cterm,
      },
      DiffDelete = {
        fg = c.red.hex,
        ctermfg = c.red.cterm,
        bg = c.dark_grey.hex,
        ctermbg = c.dark_grey.cterm,
      },
      DiffText = {
        fg = c.yellow.hex,
        ctermfg = c.yellow.cterm,
        bg = c.dark_grey.hex,
        ctermbg = c.dark_grey.cterm,
      },
      diffAdded = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      diffRemoved = { fg = c.red.hex, ctermfg = c.red.cterm },
    },

    syntax = {
      Comment = { fg = c.dark_purple.hex, ctermfg = c.dark_purple.cterm },
      Constant = { fg = c.yellow.hex, ctermfg = c.yellow.cterm },
      Identifier = { fg = c.cyan.hex, ctermfg = c.cyan.cterm },
      Statement = { fg = c.green.hex, ctermfg = c.green.cterm },
      PreProc = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      Type = { fg = c.magenta.hex, ctermfg = c.magenta.cterm },
      Special = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      Underlined = { fg = c.green.hex, ctermfg = c.green.cterm, underline = true },
      Error = { fg = c.red.hex, ctermfg = c.red.cterm },
      Ignore = { fg = c.red.hex, ctermfg = c.red.cterm },
      Delimiter = { fg = c.cream.hex, ctermfg = c.cream.cterm },
      Operator = { fg = c.magenta.hex, ctermfg = c.magenta.cterm },
      Tag = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      Debug = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      StorageClass = { fg = c.light_purple.hex, ctermfg = c.light_purple.cterm },
      String = { fg = c.cyan.hex, ctermfg = c.cyan.cterm },
      Structure = { fg = c.cyan.hex, ctermfg = c.cyan.cterm },
      Typedef = { fg = c.cyan.hex, ctermfg = c.cyan.cterm },
      Function = { fg = c.green.hex, ctermfg = c.green.cterm },
      Include = { fg = c.green.hex, ctermfg = c.green.cterm },
      Label = { fg = c.green.hex, ctermfg = c.green.cterm },
      Exception = { fg = c.orange.hex, ctermfg = c.orange.cterm },
      Keyword = { fg = c.orange.hex, ctermfg = c.orange.cterm },
      SpecialChar = { fg = c.orange.hex, ctermfg = c.orange.cterm },
      Boolean = { fg = c.yellow.hex, ctermfg = c.yellow.cterm },
      Character = { fg = c.yellow.hex, ctermfg = c.yellow.cterm },
      Float = { fg = c.yellow.hex, ctermfg = c.yellow.cterm },
      FloatBorder = { fg = c.dark_grey.hex, bold = true },
      Number = { fg = c.yellow.hex, ctermfg = c.yellow.cterm },
      Conditional = { fg = c.green.hex, ctermfg = c.green.cterm },
      Repeat = { fg = c.green.hex, ctermfg = c.green.cterm },
      Title = { fg = c.purple.hex, ctermfg = c.purple.cterm },
      Define = { fg = c.purple.hex, ctermfg = c.purple.cterm },
      Macro = { fg = c.purple.hex, ctermfg = c.purple.cterm },
      PreCondit = { fg = c.purple.hex, ctermfg = c.purple.cterm },
      SpecialComment = { link = 'Comment' },
      Todo = {
        fg = c.white.hex,
        ctermfg = c.white.cterm,
        bg = c.grey_purple.hex,
        ctermbg = c.grey_purple.cterm,
        underline = true,
      },
    },

    lang = {
      cFormat = { link = 'Title' },
      cCppOutIf1 = { link = 'Normal' },
      cCppOutIf2 = { link = 'Normal' },
      cBracket = { link = 'Title' },
      cssBraces = { link = 'Normal' },
      cssSelectorOp = { fg = c.magenta.hex, ctermfg = c.magenta.cterm },
      fortranType = { link = 'Tag' },
      fortranStructure = { link = 'Structure' },
      fortranStorageClass = { link = 'StorageClass' },
      fortranUnitHeader = { link = 'Title' },
      haskellType = { link = 'Tag' },
      haskellIdentifier = { link = 'Label' },
      haskellKeyword = { link = 'Boolean' },
      haskellDecl = { link = 'Boolean' },
      htmlTagName = { link = 'Function' },
      htmlEndTag = { link = 'Conditional' },
      htmlArg = { link = 'Tag' },
      htmlSpecialTagName = { link = 'Type' },
      javaClassDecl = { link = 'Structure' },
      javaTypeDef = { link = 'Keyword' },
      jsStorageClass = { link = 'Title' },
      jsFunction = { link = 'Function' },
      jsFuncName = { link = 'Special' },
      jsOperator = { link = 'Operator' },
      jsNull = { link = 'Constant' },
      jsGlobalObjects = { link = 'Constant' },
      jsFuncCall = { link = 'Function' },
      jsOperatorKeyword = { link = 'Operator' },
      jsExceptions = { link = 'Error' },
      jsTernaryIfOperator = { link = 'Title' },
      jsTemplateBraces = { link = 'Title' },
      jsTemplateExpression = { link = 'String' },
      texTypeStyle = { link = 'Special' },
      mkdDelimiter = { link = 'Normal' },
      phpFunction = { link = 'Function' },
      phpMethod = { link = 'Function' },
      phpType = { link = 'Constant' },
      phpIdentifier = { link = 'Type' },
      phpStringSingle = { link = 'String' },
      phpStringDouble = { link = 'String' },
      pythonOperator = { fg = c.magenta.hex, ctermfg = c.magenta.cterm },
      rubyConstant = { link = 'Constant' },
      rubyDefine = { link = 'Define' },
      rubyMethodName = { link = 'Function' },
      rubyInstanceVariable = { link = 'Tag' },
      rubyKeywordAsMethod = { link = 'Tag' },
      jsxTagName = { link = 'HTMLTagName' },
      jsxComponentName = { link = 'Tag' },
      jsxOpenPunct = { link = 'jsxTagName' },
      jsxClosePunct = { link = 'jsxOpenPunct' },
      jsxCloseString = { link = 'jsxClosePunct' },
      typescriptProp = { link = 'Tag' },
      typescriptVariable = { link = 'Title' },
      typescriptArrowFunc = { fg = c.magenta.hex, ctermfg = c.magenta.cterm },
      typescriptBraces = { link = 'Normal' },
      typescriptNumberStaticMethod = { link = 'Function' },
      typescriptNumberMethod = { link = 'Function' },
      typescriptStringStaticMethod = { link = 'Function' },
      typescriptStringMethod = { link = 'Function' },
      typescriptArrayStaticMethod = { link = 'Function' },
      typescriptArrayMethod = { link = 'Function' },
      typescriptObjectStaticMethod = { link = 'Function' },
      typescriptObjectMethod = { link = 'Function' },
      typescriptSymbolStaticMethod = { link = 'Function' },
      typescriptFunctionMethod = { link = 'Function' },
      typescriptMathStaticMethod = { link = 'Function' },
      typescriptDateStaticMethod = { link = 'Function' },
      typescriptDateMethod = { link = 'Function' },
      typescriptJSONStaticMethod = { link = 'Function' },
      typescriptRegExpMethod = { link = 'Function' },
      typescriptES6MapMethod = { link = 'Function' },
      typescriptES6SetMethod = { link = 'Function' },
      typescriptPromiseStaticMethod = { link = 'Function' },
      typescriptPromiseMethod = { link = 'Function' },
      typescriptReflectMethod = { link = 'Function' },
      typescriptIntlMethod = { link = 'Function' },
      typescriptBOMNavigatorMethod = { link = 'Function' },
      typescriptServiceWorkerMethod = { link = 'Function' },
      typescriptBOMLocationMethod = { link = 'Function' },
      typescriptBOMHistoryMethod = { link = 'Function' },
      typescriptConsoleMethod = { link = 'Function' },
      typescriptXHRMethod = { link = 'Function' },
      typescriptFileMethod = { link = 'Function' },
      typescriptFileReaderMethod = { link = 'Function' },
      typescriptFileListMethod = { link = 'Function' },
      typescriptBlobMethod = { link = 'Function' },
      typescriptURLStaticMethod = { link = 'Function' },
      typescriptSubtleCryptoMethod = { link = 'Function' },
      typescriptCryptoMethod = { link = 'Function' },
      typescriptHeadersMethod = { link = 'Function' },
      typescriptRequestMethod = { link = 'Function' },
      typescriptResponseMethod = { link = 'Function' },
      typescriptCacheMethod = { link = 'Function' },
      typescriptEncodingMethod = { link = 'Function' },
      typescriptGeolocationMethod = { link = 'Function' },
      typescriptPaymentMethod = { link = 'Function' },
      typescriptPaymentResponseMethod = { link = 'Function' },
      typescriptDOMNodeMethod = { link = 'Function' },
      typescriptDOMDocMethod = { link = 'Function' },
      typescriptDOMEventTargetMethod = { link = 'Function' },
      typescriptDOMEventMethod = { link = 'Function' },
      typescriptDOMStorageMethod = { link = 'Function' },
      typescriptDOMFormMethod = { link = 'Function' },
      vimGroupName = { link = 'Normal' },
      yamlKeyValueDelimiter = { link = 'Normal' },
      yamlBlockMappingKey = { link = 'Function' },
      vistaTag = { link = 'Conditional' },
      vistaIcon = { link = 'Identifier' },
      vistaColon = { link = 'Normal' },
      vistaScope = { link = 'Constant' },
      vistaKind = { link = 'Conditional' },
    },

    buffer = {
      BufferCurrent = {
        fg = c.greyer.hex,
        ctermfg = c.greyer.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferVisible = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferInactive = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferTabpageFill = {
        fg = c.blackish.hex,
        ctermfg = c.blackish.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferCurrentIndex = {
        fg = c.green.hex,
        ctermfg = c.green.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferVisibleIndex = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferInactiveIndex = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferCurrentMod = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferVisibleMod = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferInactiveMod = {
        fg = c.orange.hex,
        ctermfg = c.orange.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferCurrentSign = {
        fg = c.green.hex,
        ctermfg = c.green.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferVisibleSign = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferInactiveSign = {
        fg = c.dark_purple.hex,
        ctermfg = c.dark_purple.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferCurrentTarget = {
        fg = c.magenta.hex,
        ctermfg = c.magenta.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferVisibleTarget = {
        fg = c.magenta.hex,
        ctermfg = c.magenta.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
      BufferInactiveTarget = {
        fg = c.magenta.hex,
        ctermfg = c.magenta.cterm,
        bg = c.blackish.hex,
        ctermbg = c.blackish.cterm,
      },
    },
  }
end

return M
